name: cypcar
description: "CypCar - Kıbrıs Araç İlanları"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Network
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4

  # Images
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  equatable: ^2.0.7

  # Code generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.1
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk value

flutter:
  uses-material-design: true
  assets:
    - assets/images/
