name: iOS Build (Unsigned)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Verify Commit
      run: |
        echo "Derlenen Son Commit:"
        git log -1 --pretty=format:"%h - %s"
        echo "Build No: ${{ github.run_number }}"

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Clean and Install Dependencies
      run: |
        flutter clean
        flutter pub get

    - name: Build iOS (No Codesign)
      run: |
        flutter build ios --release --no-codesign

    - name: Create IPA for Sideloadly
      run: |
        rm -rf Payload
        mkdir -p Payload
        cp -RP build/ios/iphoneos/Runner.app Payload/
        # Dosya ismine run_number ekleyerek karışıklığı önlüyoruz
        zip -ry Cypcar_v${{ github.run_number }}.ipa Payload
        ls -lh Cypcar_v${{ github.run_number }}.ipa

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        # Artifact listesinde de benzersiz isim görünecek
        name: Cypcar_Build_No_${{ github.run_number }}
        path: Cypcar_v${{ github.run_number }}.ipa
